trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ARTIFACT_NAME: 'SpringBootApp'
  BUCKET_NAME: 'aws-bucket-eu-central-1'
  BUCKET_FOLDER: 'deliveries'

steps: 
- task: Maven@4
  displayName: 'Clean Build and Install'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  
- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: $(ARTIFACT_NAME)
    publishLocation: 'Container'
