trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:  
- task: BeanstalkDeployApplication@1
  inputs:
    awsCredentials: 'aws-service-connection'
    regionName: 'eu-central-1'
    applicationName: 'AwsSpringBootApp'
    environmentName: 'AwsSpringBootApp-env'
    applicationType: 's3'
    deploymentBundleBucket: 'aws-bucket-eu-central-1'
    deploymentBundleKey: 'deliveries/SimpleSpringBoot-0.0.1-SNAPSHOT.jar'
    logRequest: true
    logResponse: true