# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  ARTIFACT_NAME: 'SimpleSpringBoot'
  AWS_S3_BUCKET: 'aws-my-build-artifact'
  AWS_TARGET_FOLEDER: 'MyDeliveries'

steps:
- task: Maven@4
  displayName: 'Maven Clean and Install'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy JAR file to Artifact Staging Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact SimpleSpringBoot'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: $(ARTIFACT_NAME)
    publishLocation: 'Container'

- task: S3Upload@1
  displayName: 'Upload to AWS S3'
  inputs:
    awsCredentials: 'aws_s3_connectrion'
    regionName: 'eu-central-1'
    bucketName: $(AWS_S3_BUCKET)
    sourceFolder: '$(Build.StagingDirectory)'
    globExpressions: '**/*.jar'
    targetFolder: $(AWS_TARGET_FOLEDER)
