trigger:
- none

pool:
  vmImage: ubuntu-latest

steps: 
- task: Maven@4
  displayName: 'Clean Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Maven@4
  displayName: 'Create Build'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
  
- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'myDeploy'
    publishLocation: 'Container'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.ArtifactStagingDirectory)
      find . -name '*.jar' -exec cp -p '{}' app.jar ';'
      ls -all

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws-service-connection'
    regionName: 'eu-central-1'
    bucketName: 'aws-bucket-eu-central-1'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    globExpressions: '**/app.jar'
    targetFolder: 'deliveries'
    keyManagement: 'awsManaged'
    encryptionAlgorithm: 'AES256'
    logRequest: true
    logResponse: true
